# Generated by Django 5.2 on 2025-05-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galleryimage_skill_remove_user_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
