# Generated by Django 5.2 on 2025-05-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_gallery_images_remove_user_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
